<?xml version="1.0" encoding="utf-8"?><Database Name="UoftDatabase" Class="BuildingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP;Initial Catalog=UoftDatabase;Integrated Security=True" SettingsObjectName="Web_Scrapper.Properties.Settings" SettingsPropertyName="UoftDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Building" Member="Buildings">
    <Type Name="Building">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuildingName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BuildingCode" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Building_BuildingDistance" Member="BuildingDistances" ThisKey="Id" OtherKey="BuildingID1" Type="BuildingDistance" />
      <Association Name="Building_BuildingDistance1" Member="BuildingDistances1" ThisKey="Id" OtherKey="BuildingID2" Type="BuildingDistance" />
    </Type>
  </Table>
  <Table Name="dbo.BuildingDistances" Member="BuildingDistances">
    <Type Name="BuildingDistance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuildingID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuildingID2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WalkingDuration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WalkingDistance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TransitDuration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TransitDistance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CyclingDuration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CyclingDistance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VehicleDuration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VehicleDistance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Building_BuildingDistance" Member="Building" ThisKey="BuildingID1" OtherKey="Id" Type="Building" IsForeignKey="true" />
      <Association Name="Building_BuildingDistance1" Member="Building1" ThisKey="BuildingID2" OtherKey="Id" Type="Building" IsForeignKey="true" />
    </Type>
  </Table>
</Database>