<?xml version="1.0" encoding="utf-8"?><Database Name="UoftDatabase" Class="CourseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP;Initial Catalog=UoftDatabase;Integrated Security=True" SettingsObjectName="Web_Scrapper.Properties.Settings" SettingsPropertyName="UoftDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activity" Member="Activities">
    <Type Name="Activity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ActivityType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="Activity_InstructorToActivity" Member="InstructorToActivities" ThisKey="Id" OtherKey="ActivityID" Type="InstructorToActivity" />
      <Association Name="Activity_Session" Member="Sessions" ThisKey="Id" OtherKey="ActivityID" Type="Session" />
      <Association Name="Course_Activity" Member="Course" ThisKey="CourseID" OtherKey="Id" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Term" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="Course_Activity" Member="Activities" ThisKey="Id" OtherKey="CourseID" Type="Activity" />
    </Type>
  </Table>
  <Table Name="dbo.Instructor" Member="Instructors">
    <Type Name="Instructor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Rating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Instructor_InstructorToActivity" Member="InstructorToActivities" ThisKey="Id" OtherKey="InstructorID" Type="InstructorToActivity" />
    </Type>
  </Table>
  <Table Name="dbo.InstructorToActivity" Member="InstructorToActivities">
    <Type Name="InstructorToActivity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InstructorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Activity_InstructorToActivity" Member="Activity" ThisKey="ActivityID" OtherKey="Id" Type="Activity" IsForeignKey="true" />
      <Association Name="Instructor_InstructorToActivity" Member="Instructor" ThisKey="InstructorID" OtherKey="Id" Type="Instructor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Session" Member="Sessions">
    <Type Name="Session">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fall_BuildingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fall_RoomNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Winter_BuildingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Winter_RoomNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EndTime" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Activity_Session" Member="Activity" ThisKey="ActivityID" OtherKey="Id" Type="Activity" IsForeignKey="true" />
    </Type>
  </Table>
</Database>