//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UoftTimetableGenerator.DataModels.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=emiliokartono.database.windows.net;Initial Catalog=uoftDatabase;User " +
            "ID=emiliokartono;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False")]
        public string AzureDBConnectionString {
            get {
                return ((string)(this["AzureDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=emiliokartono.database.windows.net;Initial Catalog=uoftDatabase;User " +
            "ID=emiliokartono;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False")]
        public string uoftDatabaseConnectionString {
            get {
                return ((string)(this["uoftDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP;Initial Catalog=Uoft Database;Integrated Security=True;Connect" +
            " Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrit" +
            "e;MultiSubnetFailover=False")]
        public string LocalDBConnectionString {
            get {
                return ((string)(this["LocalDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=emiliokartono.database.windows.net;Initial Catalog=uoftDatabase;User " +
            "ID=emiliokartono;Password=Molybdenum1122;Connect Timeout=60;Encrypt=True;TrustSe" +
            "rverCertificate=False")]
        public string uoftDatabaseConnectionString1 {
            get {
                return ((string)(this["uoftDatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP;Initial Catalog=\"Uoft Database\";Integrated Security=True;Conne" +
            "ct Timeout=60;Encrypt=False;TrustServerCertificate=True")]
        public string Uoft_DatabaseConnectionString {
            get {
                return ((string)(this["Uoft_DatabaseConnectionString"]));
            }
        }
    }
}
